
package tn.gov.nashville.ws.identityproofing;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IdentityProofingService2Service", targetNamespace = "http://www.exchangenetwork.net/wsdl/sharedcromerr/identity/2", wsdlLocation = "file:/C:/StormWater_Nashville/src/main/resources/wsdl/IdentityProofingService2.wsdl")
public class IdentityProofingService2Service
    extends Service
{

    private final static URL IDENTITYPROOFINGSERVICE2SERVICE_WSDL_LOCATION;
    private final static WebServiceException IDENTITYPROOFINGSERVICE2SERVICE_EXCEPTION;
    private final static QName IDENTITYPROOFINGSERVICE2SERVICE_QNAME = new QName("http://www.exchangenetwork.net/wsdl/sharedcromerr/identity/2", "IdentityProofingService2Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/StormWater_Nashville/src/main/resources/wsdl/IdentityProofingService2.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IDENTITYPROOFINGSERVICE2SERVICE_WSDL_LOCATION = url;
        IDENTITYPROOFINGSERVICE2SERVICE_EXCEPTION = e;
    }

    public IdentityProofingService2Service() {
        super(__getWsdlLocation(), IDENTITYPROOFINGSERVICE2SERVICE_QNAME);
    }

    public IdentityProofingService2Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), IDENTITYPROOFINGSERVICE2SERVICE_QNAME, features);
    }

    public IdentityProofingService2Service(URL wsdlLocation) {
        super(wsdlLocation, IDENTITYPROOFINGSERVICE2SERVICE_QNAME);
    }

    public IdentityProofingService2Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IDENTITYPROOFINGSERVICE2SERVICE_QNAME, features);
    }

    public IdentityProofingService2Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IdentityProofingService2Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IdentityProofingService2
     */
    @WebEndpoint(name = "IdentityProofingService2Port")
    public IdentityProofingService2 getIdentityProofingService2Port() {
        return super.getPort(new QName("http://www.exchangenetwork.net/wsdl/sharedcromerr/identity/2", "IdentityProofingService2Port"), IdentityProofingService2.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IdentityProofingService2
     */
    @WebEndpoint(name = "IdentityProofingService2Port")
    public IdentityProofingService2 getIdentityProofingService2Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.exchangenetwork.net/wsdl/sharedcromerr/identity/2", "IdentityProofingService2Port"), IdentityProofingService2.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IDENTITYPROOFINGSERVICE2SERVICE_EXCEPTION!= null) {
            throw IDENTITYPROOFINGSERVICE2SERVICE_EXCEPTION;
        }
        return IDENTITYPROOFINGSERVICE2SERVICE_WSDL_LOCATION;
    }

}
