
package tn.gov.nashville.ws.identityproofing;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "SharedCromerrFault", targetNamespace = "http://www.exchangenetwork.net/schema/sharedcromerr/1")
public class SharedCromerrException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SharedCromerrFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public SharedCromerrException(String message, SharedCromerrFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public SharedCromerrException(String message, SharedCromerrFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: tn.gov.nashville.ws.identityproofing.SharedCromerrFault
     */
    public SharedCromerrFault getFaultInfo() {
        return faultInfo;
    }

}
